export const ActionTypes = {
  TRACKS_SET: 'TRACKS_SET',
  SET_HEADER: 'SET_HEADER',
  SET_HEADER_ACTIVE_TAB: 'SET_HEADER_ACTIVE_TAB',
  SET_CONTEST_RANKING: 'SET_CONTEST_RANKING',
  SET_PICKUP_UNIT: 'SET_PICKUP_UNIT',
  SET_TODAY_BEST_FRIEND: 'SET_TODAY_BEST_FRIEND',
  SET_RANKING_UNIT: 'SET_RANKING_UNIT',
  SET_COMMON_UNIT: 'SET_COMMON_UNIT',
  SET_PSYCHOLOICAL: 'SET_PSYCHOLOICAL',
  SET_EXPERT_UNIT: 'SET_EXPERT_UNIT',
  SET_TAGS: 'SET_TAGS'
}